Models/ErrorViewModel.cs
using System;

namespace SquareRootCalculator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace SquareRootCalculator.Controllers
{
    public class CalcController : Controller
    {
        public ActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Compare()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Compare(double firstNumber, double secondNumber)
        {
            double firstNumberSquareRoot = Math.Sqrt(firstNumber);
            double secondNumberSquareRoot = Math.Sqrt(secondNumber);
            if (firstNumberSquareRoot > secondNumberSquareRoot)
            {
                ViewBag.Result = $"The number {firstNumber} with Square root {firstNumberSquareRoot} has a higher square root than the number {secondNumber} with square root {secondNumberSquareRoot}";
            }
            else if (firstNumberSquareRoot < secondNumberSquareRoot)
            {
                ViewBag.Result = $"The number {secondNumber} with Square root {secondNumberSquareRoot} has a higher square root than the number {firstNumber} with square root {firstNumberSquareRoot}";
            }
            else if (firstNumberSquareRoot == secondNumberSquareRoot)
            {
                ViewBag.Result = "Both Numbers have the same Square Root. Please Enter Another Value!";
            }
            else
            {
                ViewBag.Result = "This Program Only Allows Positive Whole Numbers! Please Check Your Input.";

            }
            return View();
        }


    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SquareRootCalculator.Models;

namespace SquareRootCalculator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calc/Add.cshtml
@{
    ViewData["Title"] = "Add";
}
<h1>@ViewData["Title"]</h1>

<p>Add 2 numbers</p>

Views/Calc/Compare.cshtml
@{
    ViewData["Title"] = "Square Roots Comparison Tool";
}
<h1>@ViewData["Title"]</h1>

<h5>Compare The Square Roots of 2 Given Numbers</h5>

@{
    if(ViewBag.Result != null)
    {
        <div>
            <p><strong>Result:</strong><br> @ViewBag.Result </p> 
        </div>
    }
}

    <div class="container">
        <form asp-controller="Calc" asp-action="Compare" method="POST">
            <input type="number" name="firstNumber" placeholder="First Number">
            <input type="number" name="secondNumber" placeholder="Second Number">
            <button type="submit" class="" >Submit</button>
        </form>
    </div>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Page";
}

<div class="text-center">
    <h1 class="display-4">About</h1>
    <p>This Program Compares 2 inputted numbers and returns the one with a higher square root</p>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SquareRootCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-success bg-success border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SquareRootCalculator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse navbar-right">
                    <ul class="navbar-nav navbar-right flex-grow-1 ">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SquareRootCalculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>